
Vagrant.configure(2) do |config|

  config.vm.box = 'bento/centos-7.1'

  config.vm.network "public_network", bridge: [
    "en1: Wi-Fi (AirPort)",
    "en6: Broadcom NetXtreme Gigabit Ethernet Controller",
  ], :mac => "08002791D897"
end
