
VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = 'ubuntu/trusty64'
    config.vm.synced_folder "../../", "/test"  
    
    config.vm.define :orizon do |orizon_config|
    orizon_config.vm.network "private_network", ip: "10.10.10.10"
  end
    config.vm.provision 'puppet' do |puppet|
    puppet.manifests_path = 'manifests'
  end
end